name: inception

services:
  nginx:
    build: requirements/nginx
    networks:
      - inception-net
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    secrets:
      - tls_cert
      - tls_key
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: jchuah
      WORDPRESS_TITLE: Inception
      WORDPRESS_ADMIN_USER: jchuah
      WORDPRESS_ADMIN_EMAIL: jeremychuahtm@gmail.com
      WORDPRESS_USER: chiang
      WORDPRESS_USER_EMAIL: chiang@42.com
    networks:
      - inception-net
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: jchuah
    networks:
      - inception-net
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
    restart: unless-stopped

networks:
  inception-net:
    name: inception-net
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp_data

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db_data
 
secrets:
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  tls_cert:
    file: ../secrets/tls_cert.pem
  tls_key:
    file: ../secrets/tls_key.pem
